GET http://localhost:5000/api/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoiam9obmRvZSIsInJvbGUiOiJjdXN0b21lciIsImV4cCI6MTcyMDcwNzQ1NCwiaWF0IjoxNzIwNzAzODU0fQ.VueLW2RhtpZvfbGhhOT09f9Dc8liUXQPhBrjiDZlGco